<HandStandContentTen>:
    name: 'One-Arm Handstand Pushups'

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: "#1E1E15"
        canvas:
            Color:
                rgba: 0.5, 0.5, 0.5, 1
            Rectangle:
                size: self.size
                pos: self.pos
                source: "images/Exercise_BG2.png"

        MDTopAppBar:
            id: exercise
            title: ""
            halign: 'center'
            left_action_items: [["arrow-left", lambda x: app.root.set_current('handstand')]]

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            height: root.height
            width: root.width
            effect_cls: 'ScrollEffect'

            MDGridLayout:
                id: pullup_container
                cols: 1
                padding: 20
                spacing: 20
                adaptive_height: True
                row_default_height: 25

                MDLabel:
                    size: self.texture_size
                    font_size: 40
                    halign: 'center'
                    font_name: "fonts/Sackers-Gothic-Std-Light.ttf"
                    underline: True
                    text: "Performance"
                
                MDLabel:
                    size_hint_y: None
                    size: self.texture_size
                    font_size: 40
                    font_name: "fonts/Eurostile.ttf"
                    text: "Kick up into a handstand against a wall, and lean out to the side until you are supporting yourself with one arm, as in half one-arm handstand pushups (Level 8). Keep your body gently arched with the heels against the wall. This is the start position (fig.125). Bend at the elbow and shoulder of your supporting arm until the top of your skull very gently touches the floor. Keep your non-supporting hand ready in case you make a mistake and it has to help out. This is the finish position (fig.126). In pressing back up to the start position, some explosiveness may be needed. To help you get out of the bottom position, a kick up with the legs is permissible. Bend the knees with the feet still against the wall, and straighten them quickly to add some thrust."

                MDLabel:
                    size: self.texture_size
                    font_size: 40
                    halign: 'center'
                    font_name: "fonts/Sackers-Gothic-Std-Light.ttf"
                    underline: True
                    text: "Training Goals"

                MDLabel:
                    size_hint_y: None
                    size: self.texture_size
                    font_size: 40
                    font_name: "fonts/Eurostile.ttf"
                    text: "• Beginner standard:  1 set of 1 (Both Sides)\n• intermediate standard:  2 sets of 2 (Both Sides)\n• Progression standard:  1 sets of 5 (Both Sides)"
                
                Image:
                    size_hint_y: None
                    height: 400
                    source: "images/handimags/hand 10 fig 1.png"
                
                Image:
                    size_hint_y: None
                    height: 400
                    source: "images/handimags/hand 10 fig 2.png"
