<PullUpContentFive>:
    name: 'Full Pullups'

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: "#1E1E15"
        canvas:
            Color:
                rgba: 0.5, 0.5, 0.5, 1
            Rectangle:
                size: self.size
                pos: self.pos
                source: "images/Exercise_BG2.png"

        MDTopAppBar:
            id: exercise
            title: ""
            left_action_items: [["arrow-left", lambda x: app.root.set_current('pullups')]]

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'

            MDGridLayout:
                cols: 1
                padding: dp(20)
                spacing: dp(20)
                adaptive_height: True
                row_default_height: dp(25)
                textSize: app.root.get_screen('main').ids.bottom_nav.textSize
                imageSize: app.root.get_screen('main').ids.bottom_nav.imageSize
                    
                MDLabel:
                    size: self.texture_size
                    font_size: self.parent.textSize
                    halign: 'center'
                    font_name: "fonts/Sackers-Gothic-Std-Light.ttf"
                    underline: True
                    text: "Performance"
                
                MDLabel:
                    size_hint_y: None
                    size: self.texture_size
                    font_size: self.parent.textSize
                    font_name: "fonts/Eurostile.ttf"
                    text: "Grab hold of a horizontal bar with a shoulder width overhand grip. A slightly wider grip is acceptable-experiment to find out which width feels strongest for you. Bend at the knee and loop the ankles behind your body. Your feet should be clear of the ground. Tense the body, keep the shoulders down tight and retain a very slight (almost unnoticeable) bend in the elbows to take the stress off the arm joints and place it on the muscles instead. This is the start position (fig. 49). Bend at the elbows and shoulders until your chin passes over the bar. This is the finish position (fig. 50). Enjoy the view! Pause for a moment, before reversing the motion under full control. Don't be explosive-this means depending on momentum during the exercise. The perfect muscle-building technique is smooth. Try to take two seconds up and two seconds down, pausing for a second at the top and bottom."

                MDLabel:
                    size: self.texture_size
                    font_size: self.parent.textSize
                    halign: 'center'
                    font_name: "fonts/Sackers-Gothic-Std-Light.ttf"
                    underline: True
                    text: "Training Goals"

                MDLabel:
                    size_hint_y: None
                    size: self.texture_size
                    font_size: self.parent.textSize
                    font_name: "fonts/Eurostile.ttf"
                    text: "• Beginner standard:  1 set of 5\n• intermediate standard:  2 sets of 8\n• Progression standard:  2 sets of 10"
                
                Image:
                    size_hint_y: None
                    height: self.parent.imageSize
                    source: "images/pullimags/pull 5 fig 1.png"
                
                Image:
                    size_hint_y: None
                    height: self.parent.imageSize
                    source: "images/pullimags/pull 5 fig 2.png"

